# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bottom_notification.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


imageCounter = 1
responseData =[
    {"key":"this is a primary message","key2":"This is a secondary image"},
    {"key":"this is a another primary message","key2":"This is a another secondary image"},

]

class Ui_bottom_notification(QtWidgets.QWidget):

    def __init__(self,parent=None):
        super().__init__(parent)
        #main widget
        self.setObjectName("bottom_notification")
        self.counter = 0
        self.resize(1080, 150)
        self.leftIcon = self.style().standardIcon(QtWidgets.QStyle.SP_ArrowLeft)
        self.rightIcon = self.style().standardIcon(QtWidgets.QStyle.SP_ArrowRight)
        self.setMinimumSize(QtCore.QSize(480, 75))
        self.setMaximumSize(QtCore.QSize(1080, 150))
        self.image = QtGui.QPixmap(f"resource/{self.counter}.png")
        self.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.247368 rgba(255, 255, 255, 255), stop:0.557895 rgba(255, 255, 255, 255))")
        self.setupUi()
        
    def setupUi(self):
        #horizontal layout for notification main frame
        self.bottom_notification_hl = QtWidgets.QHBoxLayout(self)
        self.bottom_notification_hl.setObjectName("bottom_notification_hl")
        #main notification frame
        self.notification_frm = QtWidgets.QFrame(self)
        self.notification_frm.setMinimumSize(QtCore.QSize(480, 75))
        self.notification_frm.setMaximumSize(QtCore.QSize(1080, 150))
        self.notification_frm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.notification_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notification_frm.setObjectName("notification_frm")

        self.notification_frm_hl = QtWidgets.QHBoxLayout(self.notification_frm)
        self.notification_frm_hl.setContentsMargins(0, 0, 0, 0)
        self.notification_frm_hl.setSpacing(0)
        self.notification_frm_hl.setObjectName("notification_frm_hl")
        #left notification qframe
        self.left_navigate_frm = QtWidgets.QFrame(self.notification_frm)
        self.left_navigate_frm.setMinimumSize(QtCore.QSize(40, 75))
        self.left_navigate_frm.setMaximumSize(QtCore.QSize(40, 150))
        self.left_navigate_frm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_navigate_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_navigate_frm.setObjectName("left_navigate_frm")

        self.left_navigate_frm_vl = QtWidgets.QVBoxLayout(self.left_navigate_frm)
        self.left_navigate_frm_vl.setContentsMargins(0, 0, 0, 0)
        self.left_navigate_frm_vl.setSpacing(0)
        self.left_navigate_frm_vl.setObjectName("left_navigate_frm_vl")

        self.left_increment_btn = QtWidgets.QPushButton(self.left_navigate_frm)
        self.left_increment_btn.setMinimumSize(QtCore.QSize(40, 75))
        self.left_increment_btn.setMaximumSize(QtCore.QSize(40, 150))
        self.left_increment_btn.setObjectName("left_increment_btn")
        self.left_navigate_frm_vl.addWidget(self.left_increment_btn)
        self.notification_frm_hl.addWidget(self.left_navigate_frm)

        self.motificatio_text_frm = QtWidgets.QFrame(self.notification_frm)
        self.motificatio_text_frm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.motificatio_text_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.motificatio_text_frm.setObjectName("motificatio_text_frm")

        self.motificatio_text_frm_hl = QtWidgets.QHBoxLayout(self.motificatio_text_frm)
        self.motificatio_text_frm_hl.setObjectName("motificatio_text_frm_hl")

        self.icon_frm = QtWidgets.QFrame(self.motificatio_text_frm)
        self.icon_frm.setMinimumSize(QtCore.QSize(75, 75))
        self.icon_frm.setMaximumSize(QtCore.QSize(150, 150))
        self.icon_frm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.icon_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_frm.setObjectName("icon_frm")

        self.icon_frm_vl = QtWidgets.QVBoxLayout(self.icon_frm)
        self.icon_frm_vl.setObjectName("icon_frm_vl")

        self.icon_lbl = QtWidgets.QLabel(self.icon_frm)
        self.icon_lbl.setPixmap(self.image)
        self.icon_lbl.setScaledContents(True)
        self.icon_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_lbl.setObjectName("icon_lbl")
        self.icon_frm_vl.addWidget(self.icon_lbl)
        self.motificatio_text_frm_hl.addWidget(self.icon_frm)
        self.message_frm = QtWidgets.QFrame(self.motificatio_text_frm)
        self.message_frm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.message_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message_frm.setObjectName("message_frm")
        self.message_frm_vl = QtWidgets.QVBoxLayout(self.message_frm)
        self.message_frm_vl.setContentsMargins(0, 0, 0, 0)
        self.message_frm_vl.setObjectName("message_frm_vl")
        self.primary_msg_lbl = QtWidgets.QLabel(self.message_frm)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.primary_msg_lbl.setFont(font)
        self.primary_msg_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_msg_lbl.setObjectName("primary_msg_lbl")
        self.message_frm_vl.addWidget(self.primary_msg_lbl)
        self.secondary_msg_lbl = QtWidgets.QLabel(self.message_frm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.secondary_msg_lbl.setFont(font)
        self.secondary_msg_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_msg_lbl.setObjectName("secondary_msg_lbl")
        self.message_frm_vl.addWidget(self.secondary_msg_lbl)
        self.motificatio_text_frm_hl.addWidget(self.message_frm)
        self.notification_frm_hl.addWidget(self.motificatio_text_frm)
        self.right_navigate_frm = QtWidgets.QFrame(self.notification_frm)
        self.right_navigate_frm.setMinimumSize(QtCore.QSize(40, 75))
        self.right_navigate_frm.setMaximumSize(QtCore.QSize(40, 150))
        self.right_navigate_frm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_navigate_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_navigate_frm.setObjectName("right_navigate_frm")
        self.right_navigate_frm_hl = QtWidgets.QHBoxLayout(self.right_navigate_frm)
        self.right_navigate_frm_hl.setContentsMargins(0, 0, 0, 0)
        self.right_navigate_frm_hl.setSpacing(0)
        self.right_navigate_frm_hl.setObjectName("right_navigate_frm_hl")
        self.right_increment_btn = QtWidgets.QPushButton(self.right_navigate_frm)
        self.right_increment_btn.setMinimumSize(QtCore.QSize(40, 75))
        self.right_increment_btn.setMaximumSize(QtCore.QSize(40, 150))
        self.right_increment_btn.setObjectName("right_increment_btn")
        self.right_navigate_frm_hl.addWidget(self.right_increment_btn)
        self.notification_frm_hl.addWidget(self.right_navigate_frm)
        self.bottom_notification_hl.addWidget(self.notification_frm)

        self.retranslateUi()
        #QtCore.QMetaObject.connectSlotsByName(bottom_notification)
    
    
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("bottom_notification", "Form"))
        self.left_increment_btn.setIcon(self.leftIcon)
        self.left_increment_btn.clicked.connect(self.decrement)
        self.right_increment_btn.setIcon(self.rightIcon)
        self.right_increment_btn.clicked.connect(self.increment)
        self.primary_msg_lbl.setText(_translate("bottom_notification", responseData[self.counter]["key"]))
        self.secondary_msg_lbl.setText(_translate("bottom_notification",responseData[self.counter]["key2"]))

    def decrement(self):
        _retranslate = QtCore.QCoreApplication.translate
        if(self.counter > 0):
            self.counter -= 1
        else:
            print("image ended")
        self.image = QtGui.QPixmap(f"resource/{self.counter}.png")
        self.icon_lbl.setPixmap(self.image)
        try:
            self.primary_msg_lbl.setText(_retranslate("bottom_notification",responseData[self.counter]["key"]))
            self.secondary_msg_lbl.setText(_retranslate("bottom_notification",responseData[self.counter]["key2"]))
        except:
            print("response data ended")

    def increment(self):
        _retranslate = QtCore.QCoreApplication.translate
        if(self.counter != imageCounter):
            self.counter += 1
        else:
            print("image ended")
        self.image = QtGui.QPixmap(f"resource/{self.counter}.png")
        self.icon_lbl.setPixmap(self.image)
        try:
            self.primary_msg_lbl.setText(_retranslate("bottom_notification",responseData[self.counter]["key"]))
            self.secondary_msg_lbl.setText(_retranslate("bottom_notification",responseData[self.counter]["key2"]))
        except:
            print("response Data ended")

def main():
    app=QtWidgets.QApplication(sys.argv)
    main_window=Ui_bottom_notification()
    #main_window.notification.hide()
   # main_window.setSevere([
     #   "Severe1","severe2"
    #])
    main_window.show()
    sys.exit(app.exec())

if __name__ == '__main__':
    main()