from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_Form(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__(parent)
        self.logOutButton = self.style().standardIcon(QtWidgets.QStyle.SP_DialogCloseButton)
        self.helpButton = self.style().standardIcon(QtWidgets.QStyle.SP_DialogHelpButton)
        self.statusButton = self.style().standardIcon(QtWidgets.QStyle.SP_DirHomeIcon)
        self.image = QtGui.QPixmap("resource/1.png")
        self.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.247368 rgba(255, 255, 255, 255), stop:0.557895 rgba(255, 255, 255, 255))")
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(868, 484)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self)
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.close_frame = QtWidgets.QFrame(self.header_frame)
        self.close_frame.setMaximumSize(QtCore.QSize(110, 110))
        self.close_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.close_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.close_frame.setObjectName("close_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.close_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.close_frame)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setIcon(self.logOutButton)
        self.verticalLayout_2.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.close_frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.close_frame)
        self.text_frame = QtWidgets.QFrame(self.header_frame)
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.text_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.text_frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout.addWidget(self.text_frame)
        self.header_home_frame = QtWidgets.QFrame(self.header_frame)
        self.header_home_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_home_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_home_frame.setObjectName("header_home_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_home_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.header_home_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setIcon(self.helpButton)
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.header_home_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setIcon(self.statusButton)
        self.verticalLayout_4.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.header_home_frame)
        self.verticalLayout.addWidget(self.header_frame)
        self.footer_frame = QtWidgets.QFrame(self)
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.footer_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.footer_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setObjectName("label_9")
        self.label_9.setPixmap(self.image)
        self.label_9.setScaledContents(True)
        self.verticalLayout_10.addWidget(self.label_9)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setPixmap(self.image)
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.footer_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setPixmap(self.image)
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.verticalLayout_11.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.frame_10)
        self.label_15.setPixmap(self.image)
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.footer_frame)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        #self.pushButton.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "Close"))
        self.label_4.setText(_translate("Form", "26 october 2021\n20.41 (GMT)\nNetwork:connected\nAcme Cinema London"))
        #self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.label_2.setText(_translate("Form", "Help"))
        #self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.label_3.setText(_translate("Form", "Status"))
        self.label_5.setText(_translate("Form","UK\nCustomer Support: 020 8123 1234\nSales: 020 8123 1234"))
        self.label_6.setText(_translate("Form", "Germany\nCustomer Support: 020 8123 1234\nSales: 020 8123 1234"))
        self.label_7.setText(_translate("Form", "Lorem ipsum dolor sit amet"))
        self.label_8.setText(_translate("Form", "Onlie Support"))
        #self.label_9.setText(_translate("Form", "first IMage"))
        self.label_10.setText(_translate("Form", "Purchase Stock"))
        #self.label_11.setText(_translate("Form", "TextLabel"))
        self.label_12.setText(_translate("Form", "Guidance Video"))
        #self.label_13.setText(_translate("Form", "TextLabel"))
        self.label_14.setText(_translate("Form", "Install Mobile App"))
        #self.label_15.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    app=QtWidgets.QApplication(sys.argv)
    widget = Ui_Form()
    widget.show()
    sys.exit(app.exec())
